<?php $__env->startSection('title'); ?>
<title>Privacy Policy</title>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('content'); ?>
<section>
   <div class="container">
       <div class="row align-items-center">
        <p class="MsoNormal" align="center" style="text-align: center; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><b><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">PRIVACY
            POLICY<o:p></o:p></span></b></p><p class="MsoNormal" style="text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><b><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Joyflyr</span></b><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"> is committed towards safeguarding your privacy. Contact
            us </span><span lang="EN"><a href="mailto:atsupport@joyflyr.com"><span style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(17, 85, 204); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">atsupport@joyflyr.com</span></a></span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"> if you have any questions or problems regarding the use
            of your Personal Data and we will gladly assist you.<o:p></o:p></span></p><p class="MsoNormal" style="text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">By using this site or/and our services, you consent to the
            Processing of your Personal Data as described in this Privacy Policy.<o:p></o:p></span></p><p class="MsoNormal" style="text-align:justify;line-height:150%"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">This
            Privacy Policy describes how your personal information is collected, used, and
            shared when you visit or make a purchase from www.Joyflyr.com (the “Site”). <o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><b><span lang="EN" style="font-size:14.0pt;
            line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:
            &quot;Times New Roman&quot;">1.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span></b><!--[endif]--><b><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">Definitions<o:p></o:p></span></b></p><p class="MsoNormal" style="margin-left: 72pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:14.0pt;line-height:150%">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">Personal Data – any information
            relating to an identified or identifiable natural person.</span><span lang="EN" style="font-size:14.0pt;line-height:150%"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 72pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:14.0pt;line-height:150%">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">Processing – any operation or set of
            operations which is performed on Personal Data or on sets of Personal Data.</span><span lang="EN" style="font-size:14.0pt;line-height:150%"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 72pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:14.0pt;line-height:150%">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">Data subject – a natural person
            whose Personal Data is being Processed.</span><span lang="EN" style="font-size:
            14.0pt;line-height:150%"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 72pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:14.0pt;line-height:150%">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">Child – a natural person under 16
            years of age.</span><span lang="EN" style="font-size:14.0pt;line-height:150%"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 72pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:14.0pt;line-height:150%">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">We/us (either capitalized or not) –</span><span lang="EN" style="font-size:14.0pt;line-height:150%"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><b><span lang="EN" style="font-size:14.0pt;
            line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:
            &quot;Times New Roman&quot;">2.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span></b><!--[endif]--><b><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">Data Protection Principles<o:p></o:p></span></b></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size:14.0pt;line-height:150%;
            font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">We
            promise to follow the following data protection principles:<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:12.0pt;line-height:150%;color:#202228">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;
            line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:
            &quot;Times New Roman&quot;">Processing is lawful, fair, transparent. Our Processing
            activities have lawful grounds. We always consider your rights before
            Processing Personal Data. We will provide you information regarding Processing
            upon request.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:12.0pt;line-height:150%;color:#202228">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;
            line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:
            &quot;Times New Roman&quot;">Processing is limited to the purpose. Our Processing
            activities fit the purpose for which Personal Data was gathered.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:12.0pt;line-height:150%;color:#202228">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;
            line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:
            &quot;Times New Roman&quot;">Processing is done with minimal data. We only gather and
            Process the minimal amount of Personal Data required for any purpose.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:12.0pt;line-height:150%;color:#202228">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;
            line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:
            &quot;Times New Roman&quot;">Processing is limited within a time period. We will not
            store your personal data for longer than needed.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:12.0pt;line-height:150%;color:#202228">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;
            line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:
            &quot;Times New Roman&quot;">We will do our best to ensure the accuracy of data.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:12.0pt;line-height:150%;color:#202228">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;
            line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:
            &quot;Times New Roman&quot;">We will do our best to ensure the integrity and confidentiality
            of data.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:12.0pt;line-height:150%;color:#202228">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;
            line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:
            &quot;Times New Roman&quot;">In case of deletion of an account we will keep the data in
            our possession for the period not less than 180 days from the date of deletion
            of the account for the purpose of customer analytics and to improve our
            services.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><b><span lang="EN" style="font-size:14.0pt;
            line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:
            &quot;Times New Roman&quot;">3.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span></b><!--[endif]--><b><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">Data we gather<o:p></o:p></span></b></p><p class="MsoNormal" style="margin-left: 72pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">Information you have provided us
            with<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 72pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size:14.0pt;line-height:150%;
            font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">This
            might be your e-mail address, name, billing address, shipping address,
            telephone number etc – mainly information that is necessary for delivering you
            a product/service or to enhance your customer experience with us. We save the
            information you provide us with in order for you to comment or perform other
            activities on the website. This information includes, for example, your name
            and email address.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">Information automatically collected
            about you<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size:14.0pt;line-height:150%;
            font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">This
            includes information that is automatically stored by cookies and other session
            tools. For example, your shopping cart information, your IP address, your
            shopping history (if there is any) etc. This information is used to improve
            your customer experience. When you use our services or look at the contents of
            our website, your activities may be logged.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">Information that you can provide as
            per your choice<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size:14.0pt;line-height:150%;
            font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">We
            will further collect/ ask you to upload your profile picture to the profile
            which should not be vulgar, vague or against any religious sentiments of any
            individual. <o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">Publicly available information<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size:14.0pt;line-height:150%;
            font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">We
            might gather information about you that is publicly available.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 72pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">Data Which is in your opinion to
            upload:<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 72pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size:14.0pt;line-height:150%;
            font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">We
            might gather the profile picture where it would be your sole discretion to
            upload or not. The provided data must comply with the policy and which must not
            be vulgar, indecent, vague or against any religious or political sentiments.&nbsp; <o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 72pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size:14.0pt;line-height:150%;
            font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;</span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><b><span lang="EN" style="font-size:14.0pt;
            line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:
            &quot;Times New Roman&quot;">4.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span></b><!--[endif]--><b><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">How we use your Personal Data<o:p></o:p></span></b></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size:14.0pt;line-height:150%;
            font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">We
            use your Personal Data in order to:<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 72pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 12pt; line-height: 150%; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">provide
            our service to you. This includes for example registering your account;
            providing you with other products and services that you have requested;
            providing you with promotional items at your request and communicating with you
            in relation to those products and services; communicating and interacting with
            you; and notifying you of changes to any services.</span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 87pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 12pt; line-height: 150%; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">enhance
            your customer experience;</span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 87pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 12pt; line-height: 150%; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">fulfil an
            obligation under law or contract;</span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><o:p></o:p></span></p><p class="MsoNormal" style="text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">We use your Personal Data on legitimate grounds and/or
            with your Consent.<o:p></o:p></span></p><p class="MsoNormal" style="text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">On the grounds of entering into a contract or fulfilling
            contractual obligations, we Process your Personal Data for the following
            purposes:<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 51pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 12pt; line-height: 150%; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">➔<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">to
            identify you;</span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 51pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 12pt; line-height: 150%; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">➔<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">to
            provide you a service or to send/offer you a product;</span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 51pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 12pt; line-height: 150%; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">➔<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">to
            communicate either for sales or invoicing;</span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 51pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 12pt; line-height: 150%; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">➔<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">For
            delivering the order</span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 51pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 12pt; line-height: 150%; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">➔<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">For
            tracking the location to mark the completion of order.</span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><o:p></o:p></span></p><p class="MsoNormal" style="text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">On the ground of legitimate interest, we Process your
            Personal Data for the following purposes:<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 51pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 12pt; line-height: 150%; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">❖<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">to send
            you personalized offers* (from us and/or our carefully selected partners);</span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 51pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 12pt; line-height: 150%; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">❖<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">to
            administer and analyse our client base (purchasing behaviour and history) in
            order to improve the quality, variety, and availability of products/ services
            offered/provided;</span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 51pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 12pt; line-height: 150%; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">❖<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">to
            conduct questionnaires concerning client satisfaction;</span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><o:p></o:p></span></p><p class="MsoNormal" style="text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">As long as you have not informed us otherwise, we consider
            offering you products/services that are similar or same to your purchasing
            history/browsing behaviour to be in our legitimate interest.<o:p></o:p></span></p><p class="MsoNormal" style="text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">With your consent we Process your Personal Data for the
            following purposes:<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 51pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 12pt; line-height: 150%; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">➔<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">to send
            you newsletters and campaign offers (from us and/or our carefully selected
            partners);</span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 51pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 12pt; line-height: 150%; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">➔<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">for other
            purposes we have asked your consent for;</span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><o:p></o:p></span></p><p class="MsoNormal" style="text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">We Process your Personal Data in order to fulfil obligations
            rising from law and/or use your Personal Data for options provided by law. We
            reserve the right to anonymise Personal Data gathered and to use any such data.
            We will use data outside the scope of this Policy only when it is anonymised.
            We save your billing information and other information gathered about you for
            as long as needed for accounting purposes or other obligations deriving from
            law, but not longer than 10 years.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><b><span lang="EN" style="font-size:14.0pt;
            line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:
            &quot;Times New Roman&quot;">5.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span></b><!--[endif]--><b><span lang="EN" style="font-size:14.0pt;line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
            mso-fareast-font-family:&quot;Times New Roman&quot;">Who else can access your Personal
            Data<o:p></o:p></span></b></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size:14.0pt;line-height:150%;
            font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">We
            do not share your Personal Data with strangers. Personal Data about you is in
            some cases provided to our trusted partners in order to either make providing
            the service to you possible or to enhance your customer experience. We share
            your data with:<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size:12.0pt;line-height:150%;color:#202228">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size:14.0pt;
            line-height:150%;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:
            &quot;Times New Roman&quot;">Our processing partners:<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size:14.0pt;line-height:150%;
            font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">We
            will share your required information with our payment gateway partner Razorpay
            to make the payment via.PhonePe, GPay, Debit Card, Credit card or any other
            payment mode opted by you.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 12pt; line-height: 150%; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">●<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Our
            business partners:</span><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">The delivery personnel who
            will deliver your order at your address.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">We only work with
            Processing partners who are able to ensure an adequate level of protection to
            your Personal Data. We disclose your Personal Data to third parties or public
            officials when we are legally obliged to do so. We might disclose your Personal
            Data to third parties if you have consented to it or if there are other legal
            grounds for it.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><b><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(46, 57, 64); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">6.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span></b><!--[endif]--><b><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(46, 57, 64); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Cookies and other technologies we use<o:p></o:p></span></b></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">We use cookies and/or
            similar technologies to analyse customer behaviour, administer the website,
            track users’ movements, and to collect information about users. This is done in
            order to personalise and enhance your experience with us.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">A cookie is a tiny text
            file stored on your computer. Cookies store information that is used to help
            make sites work. Only we can access the cookies created by our website. You can
            control your cookies at the browser level. Choosing to disable cookies may
            hinder your use of certain functions.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; text-indent: -18pt; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><!--[if !supportLists]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">7.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">IN CASE
            OF CANCELLATION OF THE SUBSCRIPTION<o:p></o:p></span></p><p class="MsoNormal" style="margin-left: 36pt; text-align: justify; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(32, 34, 40); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">If you don't want to
            continue our services or receive the written notice about the <a name="_GoBack"></a>cancellation,
            then we would be retaining the provided personal data for the period of 180
            days.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt;text-align:justify;text-indent:
            -18.0pt;line-height:150%;mso-list:l7 level1 lfo6"><!--[if !supportLists]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">8.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">CHANGES TO THIS PRIVACY
            POLICY<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt;text-align:justify;line-height:
            150%"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">We
            may update our Privacy Policy from time to time. We will notify you of any
            changes by posting the new Privacy Policy on this page.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt;text-align:justify;line-height:
            150%"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">You
            are advised to review this Privacy Policy periodically for any changes. Changes
            to this Privacy Policy are effective when they are posted on this page.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt;text-align:justify;text-indent:
            -18.0pt;line-height:150%;mso-list:l7 level1 lfo6"><!--[if !supportLists]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">9.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;
            </span></span><!--[endif]--><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">CONTACT US<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt;text-align:justify;line-height:
            150%"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">If
            you have any questions about this Privacy Policy, please our Privacy Officer
            via the details below: support@joyflyr.com<o:p></o:p></span></p><p class="MsoNormal" style="text-align:justify;line-height:150%"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">&nbsp;</span></p><p class="MsoNormal" style="text-align:justify;line-height:150%"><span lang="EN" style="font-size: 14pt; line-height: 150%; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">&nbsp;</span></p><p class="MsoNormal" align="center" style="text-align: center; line-height: 150%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">













































































































































            </p><p class="MsoNormal"><span lang="EN">&nbsp;</span></p>
       </div>
   </div>
</section>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('inlinejs'); ?>
<script>
    $(document).on('submit','#contactform',function(e){

        e.preventDefault();
        $('#contactmessage').html('<div class="alert alert-success alert-dismissible fade show" role="alert">Thanks for your query.Admin will contact you soon.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
            $('#contactmessage').fadeIn(1000).fadeOut(5000);

    });
</script>
<?php $__env->stopSection(); ?>


<?php echo $__env->make('front.layouts.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\wamp64\www\joyflier\resources\views/front/privacypolicy.blade.php ENDPATH**/ ?>